spring:
  application:
    name: eureka-server-another

server:
  port: 7009

eureka:
  client:
    service-url:
      defaultZone:
        http://server1:7000/eureka/
  instance:
    hostname: server2

