server:
  port: 8002

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_star?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 设置上传文件的大小，否则超过限制tomcat会报错
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认10M


# 对接OSS需要知道的几个固定值
aliyun:
  oss:
    file:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      access-key-id: LTAI5tNt5PVHe2GZ217qE3Fp
      access-key-secret: jDVf9PvjxPQoLBhVy4tIybKR1QUGBS
      file-host: xxx
      bucket-name: file-test-23-bucket
