spring:
  application:
    name: eureka-consumer

server:
  port: 7008

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://server1:7000/eureka/,http://server2:7009/eureka/
